name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      CXX: 'clang++'
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        sudo sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-9 main"
        sudo apt-get update
        sudo apt-get install -y clang-9 clang-format-9
    - name: configure
      run: cmake -H. -Bbuild/ -DCLANG_FORMAT=/usr/bin/clang-format-9
    - name: lint
      run: cd build && ctest --output-on-failure -R ^test.format

  gcc:
    needs: [format]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['7', '']

        include:
        - version: '7'
          compiler: 'g++-7'

        - version: ''
          compiler: 'g++'
    env:
      CXX: "${{ matrix.compiler }}"
      CXXFLAGS: '-fsanitize=address,undefined -fuse-ld=gold'
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }} cppcheck
    - name: configure
      run: cmake -H. -Bbuild/
    - name: test
      run: cd build && ctest --output-on-failure -E ^test.format

  clang:
    needs: [format]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['5', '']

        include:
        - version: '5'
          compiler: 'clang++-5.0'
          cxxflags: '-fsanitize=address,undefined -stdlib=libc++'

        - version: ''
          compiler: 'clang++'
          cxxflags: '-fsanitize=address,undefined'
    env:
      CXX: "${{ matrix.compiler }}"
      CXXFLAGS: "${{ matrix.cxxflags }}"
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)${CXX##*${CXX%-*}} main"
        sudo apt-get update
        sudo apt-get install -y clang${CXX##*${CXX%-*}} clang-tidy${CXX##*${CXX%-*}} libc++-dev libc++abi-dev
    - name: configure
      run: cmake -H. -Bbuild/ -DCLANG_TIDY=/usr/bin/clang-tidy${CXX##*${CXX%-*}}
    - name: test
      run: cd build && ctest --output-on-failure -E ^test.format

  xcode:
    needs: [format]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -H. -Bbuild/
    - name: test
      run: cd build && ctest --output-on-failure -E ^test.format

  standalone:
    needs: [gcc, clang, xcode]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: sudo apt-get install -y tree
    - name: configure
      run: cmake -H. -Bbuild/ -DCMAKE_INSTALL_PREFIX=${PWD}/install/
    - name: deploy
      run: cmake --build build/ --target install && tree ${PWD}/install/
    - name: release
      if: github.event_name == 'release'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: standalone
        FOLDER: install/include